### ISSUE TITLE
User management CRUD (Feature)

### ISSUE THREAD

**Issue by sigrist3** [d-lama/d-lama-service#6]
**Link to User Story**
[1007](https://github.com/d-lama/.github/blob/main/mgmt/product_backlog.md#1007)

**Feature Description**
The user wants to be able to create, read, update and delete his profile.

**Additional context**
Authentication: Which solution for the authentication shall we use? API keys? Basic authentication?

**Comment by joelgrand** [comment]
After long trying to get Authentication to work with OAuth2 (incl. Swagger) I switched to the authentication mechanism with JWT Bearer Tokens. => No real disadvantage...
